app.name=Compy

app.application_id=toys.compy
app.orientation=landscape
app.version_code=32
app.version_name=11.5a

# No need to modify anything past this line!
android.enableJetifier=false
android.useAndroidX=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
